/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type InlineResponse200 struct {
	Status string `json:"status,omitempty"`
	Ack int32 `json:"ack,omitempty"`
	Do int32 `json:"do,omitempty"`
	Values InlineResponse200Values `json:"values,omitempty"`
}
