/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type DeviceDataSensor struct {
	Key map[string]interface{} `json:"key,omitempty"`
	Value map[string]interface{} `json:"value,omitempty"`
}
