/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type DevicePropertiesStatusTopic struct {
	Id string `json:"id,omitempty"`
	ConsumerGroupIndex int32 `json:"consumer-group-index,omitempty"`
}
