/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type DevicePropertiesStatusPredicate struct {
	Operation string `json:"operation,omitempty"`
	Locked bool `json:"locked,omitempty"`
	TestPropertyIndex int32 `json:"test-property-index,omitempty"`
	RefValues []map[string]interface{} `json:"ref-values,omitempty"`
}
