/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Body2 struct {
	Var0 map[string]interface{} `json:"0,omitempty"`
	Var3 map[string]interface{} `json:"3,omitempty"`
}
