/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type GroupInfo struct {
	Time int32 `json:"time,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Devices []string `json:"devices,omitempty"`
	Permissions string `json:"permissions,omitempty"`
}
