/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type DeviceInfo struct {
	Time int32 `json:"time,omitempty"`
	Id int32 `json:"id,omitempty"`
	Model DeviceInfoModel `json:"model,omitempty"`
	SerialNumber string `json:"serial-number,omitempty"`
	Firmware string `json:"firmware,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Activityout int32 `json:"activityout,omitempty"`
	FreshnessWindow int32 `json:"freshness-window,omitempty"`
	LastRcv int32 `json:"last-rcv,omitempty"`
	Permissions string `json:"permissions,omitempty"`
}
