/*
 * Manages devices through Devicelink. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type DeviceProperties struct {
	Status DevicePropertiesStatus `json:"status,omitempty"`
}
